C1_m11,H,A,H,A,H,A,A,A,A,A,H,H,H,H,H,H,A,A,H,H,A,H,A,H,H,A,A,A,H,H,H,H,-,A,A,H,H,H,A,H,A,-,A,A,A,H,A,A,H,H,A,A,A,H,A,H,A,A,A,A,H,H,H,H,H,A,H,A,A,A,A,A,-,H,A,H,A,H,H,H,A,A,H,A,H
C1_m21,H,A,H,A,H,-,A,A,-,A,H,-,H,H,H,-,-,A,H,H,A,H,A,H,H,A,-,A,-,H,H,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,-,H,A,A,-,H,A,H,A,A,A,A,H,H,-,H,H,A,H,A,A,A,A,A,H,H,A,H,A,H,H,H,A,A,H,A,H
C1_m31,H,A,H,A,H,A,A,A,A,A,H,H,H,-,H,H,A,A,H,H,A,H,A,H,-,A,A,A,H,H,H,H,A,A,A,H,H,H,A,H,-,H,A,A,A,H,A,A,H,H,-,A,A,H,-,H,A,A,H,A,H,H,A,H,H,A,H,A,A,A,A,A,H,H,A,H,A,H,H,H,A,A,H,A,-
C1_m41,H,A,H,-,H,A,A,A,A,A,H,H,H,H,H,H,-,A,H,H,A,H,A,H,H,A,A,A,-,H,H,H,A,A,A,-,H,H,A,H,A,H,A,A,A,H,A,A,H,H,A,A,A,-,A,H,-,A,-,A,H,-,H,H,H,A,-,A,A,A,A,A,H,H,A,H,A,H,H,H,A,A,H,A,H
C1_m51,H,A,H,A,H,A,A,A,A,A,H,H,H,H,H,H,A,A,H,H,A,H,A,H,H,A,-,A,-,H,H,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,H,H,A,A,A,H,A,H,A,A,A,A,H,H,-,H,H,A,H,A,A,A,A,A,H,H,A,H,A,H,H,H,A,-,H,A,H
X2_m12,H,A,H,A,H,A,A,A,A,A,H,H,H,H,H,H,A,A,H,H,A,H,A,H,H,A,A,A,H,H,A,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,H,H,A,A,A,H,A,H,A,A,A,A,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,A,A,H,H,H,A,A,H,A,H
C3_m13,H,A,H,A,H,-,A,A,A,A,H,H,A,H,H,H,A,A,-,A,A,H,A,H,H,A,A,A,H,H,A,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,H,H,A,A,A,H,A,H,-,A,H,A,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,A,A,H,H,H,A,A,H,A,H
C3_m23,H,A,H,A,H,-,A,A,A,A,H,H,A,H,H,H,A,A,-,A,A,H,A,H,H,A,A,A,-,H,A,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,H,-,A,A,A,H,-,H,A,A,A,A,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,-,A,H,H,H,A,A,H,A,H
C3_m33,H,A,H,A,H,-,A,A,A,A,H,H,A,H,H,H,A,A,-,A,A,H,A,H,H,A,A,A,H,-,A,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,-,-,A,A,A,H,-,H,A,A,A,-,A,H,H,H,H,A,H,A,A,A,A,A,H,-,A,A,A,H,H,H,A,A,H,A,H
C3_m43,H,A,H,A,H,-,A,A,A,A,H,H,A,H,H,H,A,A,-,A,A,H,A,H,H,A,A,A,H,H,A,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,-,H,A,H,A,A,H,H,H,A,A,A,A,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,A,A,H,H,H,A,A,H,A,H
X4_m14,H,A,H,A,H,A,A,A,A,A,H,H,A,H,H,H,A,A,H,H,A,H,A,H,H,A,A,A,H,H,A,H,A,A,A,-,H,H,A,-,A,H,A,A,A,H,A,A,H,H,A,A,A,H,A,H,A,A,A,-,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,A,A,H,H,A,-,A,H,A,H
X4_m24,H,A,-,A,-,A,-,A,A,A,-,H,-,H,H,H,A,A,H,H,A,H,A,H,H,A,A,A,H,H,A,H,A,A,A,H,H,H,A,-,A,H,A,A,A,H,A,A,H,H,A,A,A,H,A,H,A,-,A,-,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,A,A,H,H,A,A,A,H,A,H
S5_m15,H,A,H,A,H,A,A,A,A,A,H,H,A,H,-,H,A,A,A,H,A,H,A,H,H,A,A,A,H,H,H,H,A,A,A,H,H,H,A,H,A,-,A,A,-,H,A,A,H,H,A,A,A,H,A,H,A,A,A,A,A,H,H,H,H,A,H,A,A,A,A,A,H,H,A,A,A,H,H,A,A,A,H,A,H
X6_m16,H,A,H,A,H,A,A,A,A,A,H,H,A,H,H,H,A,-,H,H,A,H,A,H,H,A,A,A,H,H,H,H,A,A,A,H,H,H,A,H,A,H,A,A,-,H,A,A,H,H,A,A,A,H,H,H,A,A,A,A,A,H,H,H,H,H,H,A,A,A,A,A,H,H,A,A,A,H,H,-,A,A,H,A,H
X6_m26,H,A,H,A,H,-,A,A,-,A,H,H,A,-,H,H,A,-,H,H,A,H,A,H,H,A,A,A,H,H,H,H,A,A,-,H,-,H,-,H,A,-,A,A,-,H,A,A,H,H,A,A,A,H,H,H,A,A,-,A,A,H,H,H,-,H,H,A,A,-,A,-,H,-,A,A,A,H,-,A,A,A,H,A,H
X6_m36,H,A,H,A,H,A,A,A,A,A,H,-,A,H,H,H,A,-,H,H,A,H,A,H,H,A,A,A,H,H,H,H,A,A,A,H,H,-,A,H,A,H,A,A,-,H,A,A,H,H,A,A,A,H,H,H,A,A,A,A,A,H,-,H,H,H,H,A,A,A,A,A,H,H,A,A,A,H,H,A,A,A,H,A,H
X6_m46,H,A,H,A,H,A,A,A,A,A,H,H,A,H,H,H,A,-,H,H,A,H,A,H,H,A,A,A,H,H,H,H,A,A,A,H,H,H,A,H,A,-,A,A,-,H,A,A,H,H,A,A,A,H,H,H,A,A,A,A,-,H,H,H,H,H,H,A,A,A,A,A,H,H,A,A,A,H,H,A,A,A,H,A,H
S7_m17,H,A,H,A,H,A,A,A,A,A,H,H,A,H,H,H,A,A,H,-,A,H,A,H,H,A,A,A,H,H,A,H,A,A,A,H,H,H,A,H,A,H,A,A,A,H,A,A,H,H,A,A,A,H,A,H,A,A,A,A,A,H,H,H,H,H,H,A,A,-,A,A,H,H,A,A,A,H,H,H,A,A,H,A,H
S8_m18,H,A,H,H,H,A,A,A,A,H,H,H,A,A,H,H,A,A,H,H,A,H,A,H,H,A,A,A,H,H,A,A,A,A,A,H,H,H,A,H,A,H,H,H,A,H,A,A,H,H,A,A,H,H,A,H,A,A,A,A,A,H,H,H,H,H,H,A,H,A,A,A,H,H,A,A,A,H,H,H,H,A,H,A,A